{{ if gt (len .Values.secretEnv) 0 }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $.Release.Name }}-secret-env
  labels:
{{ include "takehome.labels" . | indent 4 }}
data:
{{- range $key, $val := .Values.secretEnv }}
  {{ $key }}: {{ $val | toString | b64enc | quote }}
{{- end }}
{{- end -}}
